name: WordCloud

on:
  workflow_dispatch:
  schedule:
    - cron: '0 30 * * *'

jobs:
  update-readme:
    name: Update Readme with Rainbow badges
    runs-on: ubuntu-latest
    steps:
      - uses: Parply/profile-wordcloud@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          IGNORE_REPOS: "config-files,config-files-old,.github"
          IGNORE_FILE_TYPES: ".pickle,.csv,.png,.tgz,.gz,.zip,.html,.snl,.yml,.RData,.pyptoj,.vue,.gif,__pycache__,.mod,.pdf,.Rdata,.obj,.o,.so,.mp4,.in,.mtx"
          WIDTH: "100%"
          CMAP: "hsv"
